# Generated by Django 3.1.1 on 2020-09-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('abgeordnetenwatch_id', models.IntegerField()),
                ('wikidata_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Controversy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.politician')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('controversy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.controversy')),
            ],
        ),
    ]
