# Generated by Django 3.1.1 on 2020-09-07 15:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abgeordnetenwatch_id', models.IntegerField()),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.politician')),
            ],
        ),
    ]
