# Generated by Django 3.1.1 on 2020-09-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='abgeordnetenwatch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
