# Generated by Django 3.1.1 on 2020-09-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200908_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='abgeordnetenwatch_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='abstain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='no_show',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='yes',
            field=models.IntegerField(default=0),
        ),
    ]
