# Generated by Django 3.1.1 on 2020-09-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200908_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='abstain',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='no',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='no_show',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='yes',
        ),
    ]
