# Generated by Django 3.1.1 on 2020-09-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_poll_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.IntegerField(blank=True, null=True)),
                ('no', models.IntegerField(blank=True, null=True)),
                ('abstain', models.IntegerField(blank=True, null=True)),
                ('no_show', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='result',
        ),
        migrations.AddField(
            model_name='poll',
            name='result_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pollresult'),
        ),
    ]
