# Generated by Django 3.1.1 on 2020-09-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200910_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='result_key',
            new_name='result',
        ),
    ]
