# Generated by Django 3.1.1 on 2020-09-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200910_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='abstain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='no_show',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='yes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='result',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
