# Generated by Django 3.1.1 on 2020-09-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200911_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='abstract',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
